
//
// @author hxAri (hxari)
// @create 2025-02-24 15:15
// @github https://github.com/uranite-lang/uranite
//
// Uranite Copyright (c) 2025 - hxAri <hxari@proton.me>
// Uranite Licence under GNU General Public Licence v3
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// any later version.
//
// You should have received a copy of the GNU General Public License
// along with this program. If not, see <https://www.gnu.org/licenses/>.
//

#include <cstdio>
#include <cstdlib>
#include <fmt/format.h>
#include <fstream>
#include <gtest/gtest.h>
#include <sstream>
#include <spdlog/spdlog.h>
#include <string>

/**
 * @class IntegrationTest
 * @brief Test fixture for end-to-end integration testing of the Uranite compiler.
 * * This fixture manages the lifecycle of compilation testing by creating an isolated 
 * temporary directory, executing the compiler binary via shell commands, capturing standard 
 * outputs/errors, and ensuring proper sandbox cleanup after each test case.
 */
class IntegrationTest : public ::testing::Test {
	
	protected:
		
		/**
		 * @struct CompileResult
		 * @brief Encapsulates the execution feedback from a spawned shell process.
		 */
		struct CompileResult {
			std::string output;  ///< Combined standard output and standard error stream data.
			int status;          ///< The process exit status code (0 for success).
		};
		
		/** @brief Path to the target compiler executable binary. */
		std::string compiler;
		
		/** @brief Isolated temporary directory path used for reading/writing compilation artifacts. */
		std::string temporary = "/tmp/uranite-test-integration";
		
		/**
		 * @brief Prepares the test environment before executing a test case.
		 * * Initializes the compiler binary path and guarantees the existence of 
		 * the temporary sandbox directory via shell invocation.
		 */
		void SetUp() override {
			this->compiler = "./build/uranite";
			system( fmt::format( "mkdir -p {}", this->temporary ).c_str() );
		}
		
		/**
		 * @brief Cleans up the test environment after a test case finishes execution.
		 * * Recursively purges the temporary sandbox directory to prevent artifact 
		 * leakage between test boundaries.
		 */
		void TearDown() override {
			system( fmt::format( "rm -rf {}", this->temporary ).c_str() );
		}
		
		/**
		 * @brief Writes a raw string of source code into a physical file inside the sandbox.
		 * @param name The desired source filename (e.g., "main.urn").
		 * @param code The complete payload of the source program code.
		 */
		void writeSource( const std::string& name, const std::string& code ) {
			std::ofstream f( fmt::format( "{}/{}", this->temporary, name ) );
			f << code;
		}
		
		/**
		 * @brief Invokes the compiler binary to build an executable from the given source file.
		 * @param name The filename of the source code stored in the sandbox.
		 * @return CompileResult The status code and compiler diagnostics output.
		 */
		CompileResult compile( const std::string& name ) {
			std::string src( fmt::format( "{}/{}", this->temporary, name ) );
			std::string bin( fmt::format( "{}/out", this->temporary ) );
			std::string cmd( fmt::format(  "{} {} -o {} 2>&1", this->compiler, src, bin ) );
			return this->runCmd( cmd );
		}
		
		/**
		 * @brief Executes the compiled binary artifact generated by the compile phase.
		 * @return CompileResult The runtime exit code and stdout/stderr output of the compiled program.
		 */
		CompileResult run() {
			return this->runCmd( fmt::format( "{}/out 2>&1", this->temporary ) );
		}
		
		/**
		 * @brief Helper to write, compile, and execute a program for positive validation tests.
		 * * If the compilation phase fails, it aborts immediately and returns the compilation failure details.
		 * @param name The designated source file name.
		 * @param code The source code text.
		 * @return CompileResult The runtime results if compilation succeeds, otherwise the compilation errors.
		 */
		CompileResult compileAndRun( const std::string& code ) {
			std::string filename( "test-integration.urn" );
			this->writeSource( filename, code );
			CompileResult cr = this->compile( filename );
			if( cr.status != 0 ) {
				return cr;
			}
			return this->run();
		}
		
		/**
		 * @brief Helper designed for negative testing where compilation is expected to fail.
		 * @param name The designated source file name.
		 * @param code The invalid source code text expected to trigger errors.
		 * @return CompileResult The compilation result containing expected error messages and non-zero code.
		 */
		CompileResult compileShouldFail( const std::string& code ) {
			std::string filename( "test-integration.urn" );
			this->writeSource( filename, code );
			return this->compile( filename );
		}
		
		/**
		 * @brief Helper to compile and run a program, aggregating both compile-time and runtime outputs.
		 * @param name The designated source file name.
		 * @param code The source code text.
		 * @return CompileResult Combined outputs from both compilation and runtime execution logs.
		 */
		CompileResult compileAndRunFull( const std::string& code ) {
			std::string filename( "test-integration.urn" );
			this->writeSource( filename, code );
			CompileResult cr = this->compile( filename );
			if( cr.status != 0 ) {
				return cr;
			}
			CompileResult rr = this->run();
			rr.output = cr.output + rr.output;
			return rr;
		}
		
	private:
		
		/**
		 * @brief Low-level utility to execute a shell command using an sub-process pipe.
		 * * Captures the target output safely chunk-by-chunk and extracts the proper 
		 * native macro translation of the shell exit status.
		 * @param cmd The raw shell command string to execute.
		 * @return CompileResult Synchronous results of the command execution.
		 */
		CompileResult runCmd( const std::string& cmd ) {
			CompileResult result;
			FILE* pipe = popen( cmd.c_str(), "r" );
			if( !pipe ) { 
				result.status = -1; 
				return result; 
			}
			char buf[256];
			while( fgets( buf, sizeof( buf ), pipe ) ) {
				result.output += buf;
			}
			result.status = pclose( pipe );
			result.status = WEXITSTATUS( result.status );
			return result;
		}
	
};

TEST_F( IntegrationTest, Any ) {
}

TEST_F( IntegrationTest, BorrowCheckerDoubleFree ) {
	IntegrationTest::CompileResult compiled = this->compileShouldFail(
		"package main\n"
		"class Box:\n"
		"    public I64 value\n"
		"public function main() -> I32:\n"
		"    Box b = new Box()\n"
		"    delete b\n"
		"    delete b\n"
		"    return 0\n"
	);
	EXPECT_NE( compiled.status, 0 );
	EXPECT_NE( compiled.output.find( "double free" ), std::string::npos );
}

TEST_F( IntegrationTest, BreakInWhile ) {
	IntegrationTest::CompileResult compiled = this->compileAndRun(
		"package main\n"
		"extern function printf( String fmt, ... ) -> I32\n"
		"public function main() -> I32:\n"
		"    I64 i = 0\n"
		"    while True:\n"
		"        if i >= 5:\n"
			"            break\n"
		"        printf( \"%d \", i )\n"
		"        i = i + 1\n"
		"    return 0\n"
	);
	EXPECT_EQ( compiled.status, 0 );
	EXPECT_NE( compiled.output.find( "0 1 2 3 4" ), std::string::npos );
}

TEST_F( IntegrationTest, ClassConstructorAndMethod ) {
	IntegrationTest::CompileResult compiled = this->compileAndRun(
		"package main\n"
		"extern function printf( String fmt, ... ) -> I32\n"
		"class Point:\n"
		"    public I64 x\n"
		"    public I64 y\n"
		"    public function Point( self, I64 x, I64 y ) -> Void:\n"
		"        self.x = x\n"
		"        self.y = y\n"
		"public function main() -> I32:\n"
		"    Point pt = new Point( 10, 20 )\n"
		"    printf( \"%d %d\\n\", pt.x, pt.y )\n"
		"    return 0\n"
	);
	EXPECT_EQ( compiled.status, 0 );
	EXPECT_NE( compiled.output.find( "10 20" ), std::string::npos );
}

TEST_F( IntegrationTest, CompoundAssignOnMember ) {
	IntegrationTest::CompileResult compiled = this->compileAndRun(
		"package main\n"
		"extern function printf( String fmt, ... ) -> I32\n"
		"class Point:\n"
		"    public I64 x\n"
		"    public I64 y\n"
		"    public function Point( self, I64 x, I64 y ) -> Void:\n"
		"        self.x = x\n"
		"        self.y = y\n"
		"public function main() -> I32:\n"
		"    Point p = new Point( 10, 20 )\n"
		"    p.x += 5\n"
		"    p.y -= 3\n"
		"    printf( \"%d %d\\n\", p.x, p.y )\n"
		"    return 0\n"
	);
	EXPECT_EQ( compiled.status, 0 );
	EXPECT_NE( compiled.output.find( "15 17" ), std::string::npos );
}

TEST_F( IntegrationTest, ContinueInLoop ) {
	IntegrationTest::CompileResult compiled = this->compileAndRun(
		"package main\n"
		"extern function printf( String fmt, ... ) -> I32\n"
		"public function main() -> I32:\n"
		"    for I64 i = 0; i < 6; i++:\n"
		"        if i % 2 == 0:\n"
		"            continue\n"
		"        printf( \"%d \", i )\n"
		"    return 0\n"
	);
	EXPECT_EQ( compiled.status, 0 );
	EXPECT_NE( compiled.output.find( "1 3 5" ), std::string::npos );
}

TEST_F( IntegrationTest, CStyleForLoop ) {
	IntegrationTest::CompileResult compiled = this->compileAndRun(
		"package main\n"
		"extern function printf( String fmt, ... ) -> I32\n"
		"public function main() -> I32:\n"
		"    for I64 i = 0; i < 3; i += 1:\n"
		"        printf( \"%d \", i )\n"
		"    return 0\n"
	);
	EXPECT_EQ( compiled.status, 0 );
	EXPECT_NE( compiled.output.find( "0 1 2" ), std::string::npos );
}

TEST_F( IntegrationTest, CStyleForWithIncrement ) {
	IntegrationTest::CompileResult compiled = this->compileAndRun(
		"package main\n"
		"extern function printf( String fmt, ... ) -> I32\n"
		"public function main() -> I32:\n"
		"    I64 sum = 0\n"
		"    for I64 i = 1; i <= 10; i++:\n"
		"        sum += i\n"
		"    printf( \"%d\\n\", sum )\n"
		"    return 0\n"
	);
	EXPECT_EQ( compiled.status, 0 );
	EXPECT_NE( compiled.output.find( "55" ), std::string::npos );
}

TEST_F( IntegrationTest, DeferStatement ) {
	IntegrationTest::CompileResult compiled = this->compileAndRun(
		"package main\n"
		"extern function puts( String s ) -> I32\n"
		"public function main() -> I32:\n"
		"    puts( \"start\" )\n"
		"    defer:\n"
		"        puts( \"defer1\" )\n"
		"    defer:\n"
		"        puts( \"defer2\" )\n"
		"    puts( \"end\" )\n"
		"    return 0\n"
	);
	EXPECT_EQ( compiled.status, 0 );
	EXPECT_NE( compiled.output.find( "start" ), std::string::npos );
	EXPECT_NE( compiled.output.find( "end" ), std::string::npos );
	EXPECT_NE( compiled.output.find( "defer2" ), std::string::npos );
	EXPECT_NE( compiled.output.find( "defer1" ), std::string::npos );
	EXPECT_LT( compiled.output.find( "defer2" ), compiled.output.find( "defer1" ) );
}

TEST_F( IntegrationTest, DeferInLoopWithBreak ) {
	IntegrationTest::CompileResult compiled = this->compileAndRun(
		"package main\n"
		"extern function puts( String s ) -> I32\n"
		"public function main() -> I32:\n"
		"    I64 counter = 0\n"
		"    while counter < 5:\n"
		"        defer:\n"
		"            puts( \"cleanup\" )\n"
		"        if counter == 2:\n"
		"            break\n"
		"        counter = counter + 1\n"
		"    puts( \"done\" )\n"
		"    return 0\n"
	);
	EXPECT_EQ( compiled.status, 0 );
	EXPECT_NE( compiled.output.find( "done" ), std::string::npos );
	size_t firstCleanup = compiled.output.find( "cleanup" );
	EXPECT_NE( firstCleanup, std::string::npos );
	size_t secondCleanup = compiled.output.find( "cleanup", firstCleanup + 1 );
	EXPECT_NE( secondCleanup, std::string::npos );
	size_t thirdCleanup = compiled.output.find( "cleanup", secondCleanup + 1 );
	EXPECT_NE( thirdCleanup, std::string::npos );
}

TEST_F( IntegrationTest, DeferInLoopWithContinue ) {
	IntegrationTest::CompileResult compiled = this->compileAndRun(
		"package main\n"
		"extern function printf( String fmt, ... ) -> I32\n"
		"public function main() -> I32:\n"
		"    for I64 iteration = 0; iteration < 4; iteration++:\n"
		"        defer:\n"
		"            printf( \"d%d \", iteration )\n"
		"        if iteration % 2 == 0:\n"
		"            continue\n"
		"    printf( \"done\" )\n"
		"    return 0\n"
	);
	EXPECT_EQ( compiled.status, 0 );
	EXPECT_NE( compiled.output.find( "d0" ), std::string::npos );
	EXPECT_NE( compiled.output.find( "d1" ), std::string::npos );
	EXPECT_NE( compiled.output.find( "d2" ), std::string::npos );
	EXPECT_NE( compiled.output.find( "d3" ), std::string::npos );
	EXPECT_NE( compiled.output.find( "done" ), std::string::npos );
}

TEST_F( IntegrationTest, DeleteAndHeap ) {
	IntegrationTest::CompileResult compiled = this->compileAndRun(
		"package main\n"
		"extern function printf( String fmt, ... ) -> I32\n"
		"class Box:\n"
		"    public I64 value\n"
		"    public function Box( self, I64 v ) -> Void:\n"
		"        self.value = v\n"
		"public function main() -> I32:\n"
		"    Box b = new Box( 42 )\n"
		"    printf( \"%d\\n\", b.value )\n"
		"    delete b\n"
		"    return 0\n"
	);
	EXPECT_EQ( compiled.status, 0 );
	EXPECT_NE( compiled.output.find( "42" ), std::string::npos );
}

TEST_F( IntegrationTest, ElifChain ) {
	IntegrationTest::CompileResult compiled = this->compileAndRun(
		"package main\n"
		"extern function printf( String fmt, ... ) -> I32\n"
		"public function classify( I64 n ) -> Void:\n"
		"    if n < 0:\n"
		"        printf( \"neg\" )\n"
		"    elif n == 0:\n"
		"        printf( \"zero\" )\n"
		"    elif n < 10:\n"
		"        printf( \"small\" )\n"
		"    else:\n"
		"        printf( \"big\" )\n"
		"public function main() -> I32:\n"
		"    classify( -1 )\n"
		"    printf( \" \" )\n"
		"    classify( 0 )\n"
		"    printf( \" \" )\n"
		"    classify( 5 )\n"
		"    printf( \" \" )\n"
		"    classify( 100 )\n"
		"    return 0\n"
	);
	EXPECT_EQ( compiled.status, 0 );
	EXPECT_NE( compiled.output.find( "neg zero small big" ), std::string::npos );
}

TEST_F( IntegrationTest, EnumAndMatch ) {
	IntegrationTest::CompileResult compiled = this->compileAndRun(
		"package main\n"
		"extern function puts( String s ) -> I32\n"
		"enum Direction:\n"
		"    unit North\n"
		"    unit South\n"
		"    unit East\n"
		"    unit West\n"
		"public function describe( Direction d ) -> Void:\n"
		"    match d in \\\n"
		"        Direction.North => puts( \"N\" ),\\\n"
		"        Direction.East => puts( \"E\" ),\\\n"
		"        Direction.South => puts( \"S\" ),\\\n"
		"        Direction.West => puts( \"W\" ),\\\n"
		"        * => 0\n"
		"public function main() -> I32:\n"
		"    Direction d = Direction.East\n"
		"    describe( d )\n"
		"    return 0\n"
	);
	EXPECT_EQ( compiled.status, 0 );
	EXPECT_NE( compiled.output.find( "E" ), std::string::npos );
}

TEST_F( IntegrationTest, EnumLegacyAndUnitMixed ) {
	IntegrationTest::CompileResult compiled = this->compileAndRun(
		"package main\n"
		"extern function puts( String s ) -> I32\n"
		"enum Status:\n"
		"    unit Active\n"
		"    unit Inactive\n"
		"public function describe( Status s ) -> Void:\n"
		"    match s in \\\n"
		"        Status.Active => puts( \"active\" ), \\\n"
		"        Status.Inactive => puts( \"inactive\" ), \\\n"
		"        * => 0\n"
		"public function main() -> I32:\n"
		"    Status s = Status.Active\n"
		"    describe( s )\n"
		"    return 0\n"
	);
	EXPECT_EQ( compiled.status, 0 );
	EXPECT_NE( compiled.output.find( "active" ), std::string::npos );
}

TEST_F( IntegrationTest, EnumWithBackedType ) {
	IntegrationTest::CompileResult compiled = this->compileAndRun(
		"package main\n"
		"extern function puts( String s ) -> I32\n"
		"enum Color backed I64:\n"
		"    unit Red 1\n"
		"    unit Green 2\n"
		"    unit Blue 3\n"
		"public function describe( Color c ) -> Void:\n"
		"    match c in \\\n"
		"        Color.Red => puts( \"R\" ), \\\n"
		"        Color.Green => puts( \"G\" ), \\\n"
		"        Color.Blue => puts( \"B\" ), \\\n"
		"        * => 0\n"
		"public function main() -> I32:\n"
		"    Color c = Color.Green\n"
		"    describe( c )\n"
		"    return 0\n"
	);
	EXPECT_EQ( compiled.status, 0 );
	EXPECT_NE( compiled.output.find( "G" ), std::string::npos );
}

TEST_F( IntegrationTest, EnumWithUnitKeyword ) {
	IntegrationTest::CompileResult compiled = this->compileAndRun(
		"package main\n"
		"extern function puts( String s ) -> I32\n"
		"enum Direction:\n"
		"    unit North\n"
		"    unit South\n"
		"    unit East\n"
		"    unit West\n"
		"public function describe( Direction d ) -> Void:\n"
		"    match d in \\\n"
		"        Direction.North => puts( \"N\" ), \\\n"
		"        Direction.East => puts( \"E\" ), \\\n"
		"        Direction.South => puts( \"S\" ), \\\n"
		"        Direction.West => puts( \"W\" ), \\\n"
		"        * => 0\n"
		"public function main() -> I32:\n"
		"    Direction d = Direction.East\n"
		"    describe( d )\n"
		"    return 0\n"
	);
	EXPECT_EQ( compiled.status, 0 );
	EXPECT_NE( compiled.output.find( "E" ), std::string::npos );
}

TEST_F( IntegrationTest, FinalClassRejected ) {
	IntegrationTest::CompileResult compiled = this->compileShouldFail(
		"package main\n"
		"final class Singleton:\n"
		"    public I64 value\n"
		"class Extended extends Singleton:\n"
		"    public I64 extra\n"
		"public function main() -> I32:\n"
		"    return 0\n"
	);
	EXPECT_NE( compiled.status, 0 );
	EXPECT_NE( compiled.output.find( "cannot extend final class" ), std::string::npos );
}

TEST_F( IntegrationTest, FinallyAlwaysRuns ) {
	IntegrationTest::CompileResult compiled = this->compileAndRun(
		"package main\n"
		"from uranite.errors import Error\n"
		"extern function puts( String s ) -> I32\n"
		"public function main() -> I32:\n"
		"    try:\n"
		"        raise new Error( \"boom\" )\n"
		"    except as e:\n"
		"        puts( \"caught\" )\n"
		"    finally:\n"
		"        puts( \"cleanup\" )\n"
		"    return 0\n"
	);
	EXPECT_EQ( compiled.status, 0 );
	EXPECT_NE( compiled.output.find( "caught" ), std::string::npos );
	EXPECT_NE( compiled.output.find( "cleanup" ), std::string::npos );
}

TEST_F( IntegrationTest, FizzBuzz ) {
	IntegrationTest::CompileResult compiled = this->compileAndRun(
		"package main\n"
		"extern function printf( String fmt, ... ) -> I32\n"
		"public function fizzbuzz( I64 n ) -> Void:\n"
		"    for I64 i = 1; i <= n; i++:\n"
		"        if i % 15 == 0:\n"
		"            printf( \"FB \" )\n"
		"        elif i % 3 == 0:\n"
		"            printf( \"F \" )\n"
		"        elif i % 5 == 0:\n"
		"            printf( \"B \" )\n"
		"        else:\n"
		"            printf( \"%d \", i )\n"
		"public function main() -> I32:\n"
		"    fizzbuzz( 15 )\n"
		"    return 0\n"
	);
	EXPECT_EQ( compiled.status, 0 );
	EXPECT_NE( compiled.output.find( "1 2 F 4 B F 7 8 F B 11 F 13 14 FB" ), std::string::npos );
}

TEST_F( IntegrationTest, ForwardDeclaration ) {
	IntegrationTest::CompileResult compiled = this->compileAndRun(
		"package main\n"
		"extern function printf( String fmt, ... ) -> I32\n"
		"class Point;\n"
		"class Point:\n"
		"    public I64 x\n"
		"    public I64 y\n"
		"    public function Point( self, I64 x, I64 y ) -> Void:\n"
		"        self.x = x\n"
		"        self.y = y\n"
		"public function main() -> I32:\n"
		"    Point p = new Point( 3, 4 )\n"
		"    printf( \"%d %d\\n\", p.x, p.y )\n"
		"    return 0\n"
	);
	EXPECT_EQ( compiled.status, 0 );
	EXPECT_NE( compiled.output.find( "3 4" ), std::string::npos );
}

TEST_F( IntegrationTest, GenericClassBasic ) {
	IntegrationTest::CompileResult compiled = this->compileAndRun(
		"package main\n"
		"extern function printf( String fmt, ... ) -> I32\n"
		"class Box<T>:\n"
		"    public T value\n"
		"    public function Box( self, T value ) -> Void:\n"
		"        self.value = value\n"
		"    public function getValue( self ) -> T:\n"
		"        return self.value\n"
		"public function main() -> I32:\n"
		"    Box<I64> b = new Box<I64>( 42 )\n"
		"    printf( \"%d\\n\", b.getValue() )\n"
		"    return 0\n"
	);
	EXPECT_EQ( compiled.status, 0 );
	EXPECT_NE( compiled.output.find( "42" ), std::string::npos );
}

TEST_F( IntegrationTest, HelloWorld ) {
	IntegrationTest::CompileResult compiled = this->compileAndRun(
		"package main\n"
		"extern function puts( String s ) -> I32\n"
		"public function main() -> I32:\n"
		"    puts( \"Hello, World!\" )\n"
		"    return 0\n"
	);
	EXPECT_EQ( compiled.status, 0 );
	EXPECT_NE( compiled.output.find( "Hello, World!" ), std::string::npos );
}

TEST_F( IntegrationTest, InclusiveRangeForLoop ) {
	IntegrationTest::CompileResult compiled = this->compileAndRun(
		"package main\n"
		"extern function printf( String fmt, ... ) -> I32\n"
		"public function main() -> I32:\n"
		"    for I64 i in 1...5:\n"
		"        printf( \"%d \", i )\n"
		"    return 0\n"
	);
	EXPECT_EQ( compiled.status, 0 );
	EXPECT_NE( compiled.output.find( "1 2 3 4 5" ), std::string::npos );
}

TEST_F( IntegrationTest, IncrementDecrement ) {
	IntegrationTest::CompileResult compiled = this->compileAndRun(
		"package main\n"
		"extern function printf( String fmt, ... ) -> I32\n"
		"public function main() -> I32:\n"
		"    for I64 i = 0; i < 3; i++:\n"
		"        printf( \"%d \", i )\n"
		"    return 0\n"
	);
	EXPECT_EQ( compiled.status, 0 );
	EXPECT_NE( compiled.output.find( "0 1 2" ), std::string::npos );
}

TEST_F( IntegrationTest, InheritanceWithOverride ) {
	IntegrationTest::CompileResult compiled = this->compileAndRun(
		"package main\n"
		"extern function printf( String fmt, ... ) -> I32\n"
		"class Animal:\n"
		"    public String name\n"
		"    public function Animal( self, String name ) -> Void:\n"
		"        self.name = name\n"
		"    public virtual function speak( self ) -> Void:\n"
		"        printf( \"Animal\\n\" )\n"
		"class Dog extends Animal:\n"
		"    public function Dog( self, String name ) -> Void:\n"
		"        self.name = name\n"
		"    public override function speak( self ) -> Void:\n"
		"        printf( \"Woof\\n\" )\n"
		"public function main() -> I32:\n"
		"    Dog d = new Dog( \"Rex\" )\n"
		"    d.speak()\n"
		"    return 0\n"
	);
	EXPECT_EQ( compiled.status, 0 );
	EXPECT_NE( compiled.output.find( "Woof" ), std::string::npos );
}

TEST_F( IntegrationTest, InheritedMethodResolution ) {
	IntegrationTest::CompileResult compiled = this->compileAndRun(
		"package main\n"
		"extern function printf( String fmt, ... ) -> I32\n"
		"class Animal:\n"
		"    public I64 legs\n"
		"    public function Animal( self, I64 legs ) -> Void:\n"
		"        self.legs = legs\n"
		"    public function getLegs( self ) -> I64:\n"
		"        return self.legs\n"
		"class Dog extends Animal:\n"
		"    public String breed\n"
		"    public function Dog( self, String breed ) -> Void:\n"
		"        self.legs = 4\n"
		"        self.breed = breed\n"
		"public function main() -> I32:\n"
		"    Dog d = new Dog( \"Labrador\" )\n"
		"    printf( \"%d\\n\", d.getLegs() )\n"
		"    return 0\n"
	);
	EXPECT_EQ( compiled.status, 0 );
	EXPECT_NE( compiled.output.find( "4" ), std::string::npos );
}

TEST_F( IntegrationTest, InheritedPropertyAccess ) {
	IntegrationTest::CompileResult compiled = this->compileAndRun(
		"package main\n"
		"extern function printf( String fmt, ... ) -> I32\n"
		"class Base:\n"
		"    public I64 x\n"
		"    public function Base( self, I64 x ) -> Void:\n"
		"        self.x = x\n"
		"class Child extends Base:\n"
		"    public I64 y\n"
		"    public function Child( self, I64 x, I64 y ) -> Void:\n"
		"        self.x = x\n"
		"        self.y = y\n"
		"class Grandchild extends Child:\n"
		"    public I64 z\n"
		"    public function Grandchild( self, I64 x, I64 y, I64 z ) -> Void:\n"
		"        self.x = x\n"
		"        self.y = y\n"
		"        self.z = z\n"
		"public function main() -> I32:\n"
		"    Grandchild g = new Grandchild( 1, 2, 3 )\n"
		"    printf( \"%d %d %d\\n\", g.x, g.y, g.z )\n"
		"    return 0\n"
	);
	EXPECT_EQ( compiled.status, 0 );
	EXPECT_NE( compiled.output.find( "1 2 3" ), std::string::npos );
}
